# dep will cache dependencies and only update when package.json changes
FROM node:14 as dep

# Create a working directory and copy the source code into it
WORKDIR /app

COPY ./front/package.json .

# Install dependencies
RUN npm install

FROM node:14 as builder

WORKDIR /app

COPY --from=dep ./app/node_modules ./node_modules
COPY ./front .

# Build the application
RUN npm run build

RUN ls -a /app/dist/

# Use nginx as the base image
FROM nginx

# Copy nginx config file
COPY /front/nginx.conf /etc/nginx/nginx.conf

# Copy the built files from the previous image
COPY --from=builder /app/dist/ /app

EXPOSE 5173

# Start nginx
CMD ["nginx", "-g", "daemon off;"]