version: "3.8"
services:
  # backend:
  #   build: 
  #   context: .
  #   dockerfile: backend/Dockerfile
  # ports:
  #   - "8000:8000"
  # environment:
  #   - DATABASE_URL=postgres://postgres:password@db:5432/mydb
  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "5173:5173"
    # depends_on:
    #   - backend
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"