version: "3.8"
services:
  backend-dep-build-dev:
    build:
      context: .
      dockerfile: back/docker/Dockerfile.dep.dev
  backend-build-dev:
    build: 
      context: .
      dockerfile: back/docker/Dockerfile.build.dev
    depends_on:
      - backend-dep-build-dev
  backend:
    build:
      context: .
      dockerfile: back/docker/Dockerfile.dev
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
    networks:
      - my-network
    depends_on:
      - backend-dep-build-dev
      - backend-build-dev
  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - my-network
  proxy:
    image: nginx:latest
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway:  172.28.0.1


  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"