FROM rust:alpine

RUN apk add --no-cache musl-dev
WORKDIR /opt

RUN cargo new --bin back

WORKDIR /opt/back

COPY ./back/Cargo.toml ./Cargo.toml

RUN cargo build --release

# Without removing the final compiled executable, 
# Cargo will not rebuild it with the new source files
RUN rm ./target/release/deps/back*